name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Run tests
        run: go test ./...
        # uses: actions/setup-go@v6
        # with:
        #   go-version: "1.26.0"

      - name: Exit successfully
        run: (exit 0)
